using System.Text;
using System.Text.RegularExpressions;

namespace SteamWrapper.Deployment;

internal sealed record SteamLaunchChange(string Path, byte[] Before, byte[] After, int Count);
internal sealed record SteamLaunchPlan(IReadOnlyList<SteamLaunchChange> Changes, int UnrecognizedReferences);

/// <summary>Removes only the exact launch command generated by SteamWrapper, preserving all other VDF bytes.</summary>
internal static class SteamLaunchRestoration
{
    private static readonly UTF8Encoding Utf8 = new(false, true);
    private const int MaximumBytes = 32 * 1024 * 1024;

    internal static SteamLaunchPlan Inspect(string steamRoot, string dataRoot, string? selectedAppId = null,
        CancellationToken cancellationToken = default, string? selectedProfileKey = null)
    {
        SafePaths.CheckAncestors(steamRoot);
        if (!Directory.Exists(Path.Combine(steamRoot, "steamapps")))
            throw new InvalidDataException("Steam could not be located for launch-option restoration.");
        var userdata = Path.Combine(steamRoot, "userdata");
        SafePaths.CheckAncestors(userdata);
        var changes = new List<SteamLaunchChange>();
        var unknown = 0;
        var selectedIdentifiers = new[] { selectedAppId, selectedProfileKey }.OfType<string>().Distinct(StringComparer.Ordinal).ToArray();
        if (!Directory.Exists(userdata)) return new(changes, unknown);
        var accounts = Directory.GetDirectories(userdata).Where(path =>
            Path.GetFileName(path).All(char.IsAsciiDigit)).Take(129).ToArray();
        if (accounts.Length > 128) throw new InvalidDataException("Steam account inventory exceeds its limit.");
        foreach (var account in accounts)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var path = Path.Combine(account, "config", "localconfig.vdf");
            SafePaths.CheckAncestors(path);
            if (!File.Exists(path)) continue;
            if (Directory.EnumerateFiles(Path.GetDirectoryName(path)!, "localconfig.vdf.steamwrapper-backup-*").Any())
                throw new InvalidDataException("An interrupted Steam restoration backup needs review before removing launch integration.");
            var bytes = ReadBounded(path);
            var text = Utf8.GetString(bytes);
            var entries = new VdfReader(text).Read();
            var replacements = new List<(int Start, int Length)>();
            foreach (var entry in entries)
            {
                if (!entry.Value.Contains("SteamWrapperRunner", StringComparison.OrdinalIgnoreCase)) continue;
                var names = entry.Keys;
                // Removal also checks the profile's legacy key because Runner accepts either
                // key or app_id. Restore callers supply only the selected canonical AppID.
                var selectedPath = names.Length >= 6 && names.Take(5).SequenceEqual(
                    new[] { "UserLocalConfigStore", "Software", "Valve", "Steam", "apps" }, StringComparer.OrdinalIgnoreCase)
                    && selectedIdentifiers.Contains(names[5], StringComparer.Ordinal);
                if (selectedAppId is not null && !selectedPath && !selectedIdentifiers.Any(identifier => Regex.IsMatch(entry.Value,
                    "(?:^|\\s)\"?--appid\"?(?:\\s+|=)\"?" + Regex.Escape(identifier) + "\"?(?=\\s|$)",
                    RegexOptions.IgnoreCase | RegexOptions.CultureInvariant))) continue;
                var correctPath = names.Length == 7 &&
                    names.Take(5).SequenceEqual(new[] { "UserLocalConfigStore", "Software", "Valve", "Steam", "apps" }, StringComparer.OrdinalIgnoreCase) &&
                    names[6].Equals("LaunchOptions", StringComparison.OrdinalIgnoreCase) &&
                    names[5].All(char.IsAsciiDigit) && uint.TryParse(names[5], out var id) && id > 0;
                var expected = correctPath ? $"\"{Path.Combine(Path.GetFullPath(dataRoot), "bin", "SteamWrapperRunner.exe")}\" --appid \"{names[5]}\" -- %command%" : null;
                if (expected is not null && entry.Value.Equals(expected, StringComparison.Ordinal))
                    replacements.Add((entry.Start, entry.Length));
                else unknown++;
            }
            if (replacements.Count == 0) continue;
            var result = new StringBuilder(text);
            foreach (var replacement in replacements.OrderByDescending(item => item.Start))
                result.Remove(replacement.Start, replacement.Length).Insert(replacement.Start, "\"\"");
            changes.Add(new(path, bytes, Utf8.GetBytes(result.ToString()), replacements.Count));
        }
        return new(changes, unknown);
    }

    internal static int Restore(SteamLaunchPlan plan, string dataRoot, Func<bool> steamRunning, Action<string>? beforeReplace = null)
    {
        if (steamRunning()) throw new IOException("Close Steam normally before restoring launch options.");
        if (plan.Changes.Count == 0) return 0;
        var reserved = new List<FileStream>();
        try
        {
            // Reserve every snapshot before changing any account. Never overwrite a later edit.
            foreach (var change in plan.Changes)
            {
                SafePaths.CheckAncestors(change.Path);
                var stream = new FileStream(change.Path, FileMode.Open, FileAccess.Read, FileShare.Read | FileShare.Delete);
                reserved.Add(stream);
                if (stream.Length != change.Before.Length || !ReadBounded(stream).AsSpan().SequenceEqual(change.Before))
                    throw new IOException("Steam launch options changed after they were inspected.");
            }
            var backup = Path.Combine(dataRoot, "backups", "steam-launch-options", Guid.NewGuid().ToString("N"));
            SafePaths.CheckAncestors(backup);
            Directory.CreateDirectory(backup);
            foreach (var change in plan.Changes)
            {
                var account = Path.GetFileName(Path.GetDirectoryName(Path.GetDirectoryName(change.Path))!);
                WriteNew(Path.Combine(backup, account + "-localconfig.vdf"), change.Before);
            }
            var count = 0;
            foreach (var change in plan.Changes)
            {
                if (steamRunning()) throw new IOException("Steam started during restoration. Backups were preserved.");
                SafePaths.CheckAncestors(change.Path);
                var temporary = change.Path + ".steamwrapper-" + Guid.NewGuid().ToString("N");
                try
                {
                    WriteNew(temporary, change.After);
                    // A replacement may have changed the name even though the old file is reserved.
                    if (!ReadBounded(change.Path).AsSpan().SequenceEqual(change.Before))
                        throw new IOException("Steam launch options changed during restoration.");
                    // Preserve the actual replaced file as well as the original snapshot.
                    // A competing atomic rename can otherwise slip past a reserved read handle.
                    var account = Path.GetFileName(Path.GetDirectoryName(Path.GetDirectoryName(change.Path))!);
                    // ReplaceFile requires all three files on the same volume. Steam and
                    // LocalAppData often live on different drives; archive after replacement.
                    var replaced = change.Path + ".steamwrapper-backup-" + Guid.NewGuid().ToString("N");
                    beforeReplace?.Invoke(change.Path);
                    File.Replace(temporary, change.Path, replaced);
                    var replacedBytes = ReadBounded(replaced);
                    var archived = Path.Combine(backup, account + "-replaced.vdf");
                    WriteNew(archived, replacedBytes);
                    if (!ReadBounded(archived).AsSpan().SequenceEqual(replacedBytes))
                        throw new IOException("The restoration backup could not be verified; the adjacent original was kept.");
                    if (!replacedBytes.AsSpan().SequenceEqual(change.Before))
                        throw new IOException("A concurrent Steam edit was preserved in the restoration backup; cleanup was stopped.");
                    if (!ReadBounded(change.Path).AsSpan().SequenceEqual(change.After))
                        throw new IOException("Restored Steam launch options could not be verified.");
                    File.Delete(replaced);
                    count += change.Count;
                }
                finally { if (File.Exists(temporary)) File.Delete(temporary); }
            }
            return count;
        }
        finally { foreach (var stream in reserved) stream.Dispose(); }
    }

    private static byte[] ReadBounded(string path)
    {
        using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read | FileShare.Delete);
        return ReadBounded(stream);
    }

    private static byte[] ReadBounded(FileStream stream)
    {
        if (stream.Length > MaximumBytes) throw new InvalidDataException("Steam configuration exceeds its read limit.");
        var bytes = new byte[(int)stream.Length];
        stream.ReadExactly(bytes);
        return bytes;
    }

    private static void WriteNew(string path, byte[] bytes)
    {
        using var stream = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None);
        stream.Write(bytes);
        stream.Flush(flushToDisk: true);
    }

    private sealed record Entry(string[] Keys, string Value, int Start, int Length);
    private sealed record Token(string Value, int Start, int Length, bool Brace = false);

    // This is a bounded syntax reader, not a VDF serializer: untouched bytes stay untouched.
    private sealed class VdfReader(string text)
    {
        private int offset, tokens;
        private readonly List<Entry> entries = [];
        internal List<Entry> Read() { Block([], false); return entries; }
        private void Block(string[] parents, bool nested)
        {
            if (parents.Length > 64) throw Invalid();
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            while (Next() is { } key)
            {
                if (key.Brace && key.Value == "}" && nested) return;
                if (key.Brace || !seen.Add(key.Value)) throw Invalid();
                var value = Next() ?? throw Invalid();
                var path = parents.Append(key.Value).ToArray();
                if (value.Brace)
                {
                    if (value.Value != "{") throw Invalid();
                    Block(path, true);
                }
                else entries.Add(new(path, value.Value, value.Start, value.Length));
            }
            if (nested) throw Invalid();
        }
        private Token? Next()
        {
            while (offset < text.Length)
            {
                if (char.IsWhiteSpace(text[offset]) || offset == 0 && text[offset] == '\uFEFF') { offset++; continue; }
                if (text[offset] == '/' && offset + 1 < text.Length && text[offset + 1] == '/')
                { while (offset < text.Length && text[offset] != '\n') offset++; continue; }
                break;
            }
            if (offset == text.Length) return null;
            if (++tokens > 1_000_000) throw Invalid();
            var start = offset;
            var current = text[offset++];
            if (current is '{' or '}') return new(current.ToString(), start, 1, true);
            if (current != '"')
            {
                if (current is '[' or ']' || char.IsControl(current)) throw Invalid();
                while (offset < text.Length && !char.IsWhiteSpace(text[offset]) && text[offset] is not ('{' or '}')) offset++;
                return new(text[start..offset], start, offset - start);
            }
            var value = new StringBuilder();
            while (offset < text.Length)
            {
                current = text[offset++];
                if (current == '"') return new(value.ToString(), start, offset - start);
                if (current == '\\')
                {
                    if (offset == text.Length) throw Invalid();
                    current = text[offset++];
                    if (current is not ('\\' or '"' or 'n' or 'r' or 't')) value.Append('\\');
                    current = current switch { 'n' => '\n', 'r' => '\r', 't' => '\t', _ => current };
                }
                value.Append(current);
            }
            throw Invalid();
        }
        private static InvalidDataException Invalid() => new("Unsupported or ambiguous Steam configuration; no launch options were changed.");
    }
}
