<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SteamWrapper</AssemblyName>
    <Version>0.2.9</Version>
    <Product>SteamWrapper</Product>
    <ApplicationIcon>../../../assets/brand/steamwrapper.ico</ApplicationIcon>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PublishAot>true</PublishAot>
    <SelfContained Condition="'$(RuntimeIdentifier)' == 'win-x64'">true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SteamWrapper.Deployment/SteamWrapper.Deployment.csproj" />
  </ItemGroup>
</Project>
