<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>0.2.6</Version>
    <Product>SteamWrapper</Product>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="2.10.1" />
    <EmbeddedResource Include="../../../packaging/windows/update-trust.json" LogicalName="SteamWrapper.UpdateTrust.json" />
  </ItemGroup>
</Project>
